### ISSUE TITLE
Unable to compile TypeScript error TS7006: Parameter 'protoMsg' implicitly has an 'any' type. when building app

### ISSUE THREAD

**Issue by oskarth** [status-im/js-waku#39]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Unable to compile TS and run app. Note: didn't try to debug, just running Waku implementations based on README.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

```
> npm install
...
> npm run chat -- --staticNode /ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ

> js-waku@1.0.0 chat /home/oskarth/git/status-im/js-waku
> ts-node src/chat/index.ts "--staticNode" "/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"


/home/oskarth/git/status-im/js-waku/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/lib/waku_store/index.ts:61:36 - error TS7006: Parameter 'protoMsg' implicitly has an 'any' type.

61             response.messages.map((protoMsg) => {
                                      ~~~~~~~~

    at createTSError (/home/oskarth/git/status-im/js-waku/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/home/oskarth/git/status-im/js-waku/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/home/oskarth/git/status-im/js-waku/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/home/oskarth/git/status-im/js-waku/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/home/oskarth/git/status-im/js-waku/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/oskarth/git/status-im/js-waku/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-waku@1.0.0 chat: `ts-node src/chat/index.ts "--staticNode" "/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-waku@1.0.0 chat script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oskarth/.npm/_logs/2021-04-19T09_45_58_774Z-debug.log
```

```
> nvm version
v11.14.0
> npm version
w{ 'js-waku': '1.0.0',
  npm: '6.7.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.1.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.37.0',
  node: '11.14.0',
  openssl: '1.1.1b',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.27.0',
  v8: '7.0.276.38-node.18',
  zlib: '1.2.11' }
```

cc @D4nte

**Comment by D4nte** [comment]
Do `npm run build`.  I'll update instructions.

**Comment by oskarth** [comment]
```
> npm run build

> js-waku@1.0.0 build /home/oskarth/git/status-im/js-waku
> run-s build:*


> js-waku@1.0.0 build:1-proto /home/oskarth/git/status-im/js-waku
> buf generate

sh: buf: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! js-waku@1.0.0 build:1-proto: `buf generate`
```

**Comment by oskarth** [comment]
Installing buf from https://docs.buf.build/installation/ (Linux) seems OK but a bit annoying from developer XP POV. How much do we need it? As a JS developer I'd probably rather write JSON and leave protobuf as an implementation detail.

**Comment by oskarth** [comment]
App starts now but:

```
 js-waku@1.0.0 chat /home/oskarth/git/status-im/js-waku
> ts-node src/chat/index.ts "--staticNode" "/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"

PeerId:  PeerId {
  _id:
   Uint8Array [
     18,
     32,
     87,
     8,
     88,
     15,
     124,
     50,
     236,
     165,
     238,
     104,
     176,
     173,
     57,
     145,
     232,
     17,
     15,
     127,
     99,
     105,
     183,
     27,
     204,
     41,
     244,
     65,
     157,
     74,
     213,
     102,
     191,
     16 ],
  _idB58String: 'QmUCPZMk45XGnHLw7tBToh2GAdMqQqRYfbF7At91euf84P',
  _privKey:
   RsaPrivateKey {
     _key:
      { kty: 'RSA',
        n:
         'rciJnTZAToh-9FRF-6kZyICUGy6OJlb-Nv0SjoS3U_SJxUymVIoqMOOPFW-2lIXjxS-iPfVwi7CLl60MkxFllJUs5sF5nJU5KwR2CXusniI3h34X2igkWQuNe5EqwJw53rg2kaLcceNoWYGw1Xogv_okWnjaSDvo4HYUDWLyLf4mtP_Xwowi9IzH4qw99IPPjo0yA9KNxa1ZxjN9zdMsDcE9tmh9iUoh3-50m3LziVyQ7pgEto6p3xM72cfMY7PuiEihLa6Lbt0RGmGmxnroLrY-aenXRsbjJzRVdFUq5xoYuZhCH_gfcgXU3KgmZW2nizvX0xttzK5FsC84s587gQ',
        e: 'AQAB',
        d:
         'Iv6H35WGG4pW7kJuGUAzBfIGYPbd_xBzfoU1kGdfN1O9znIh6FIuLswUCwAE5yGS_SkbZZigAjEZ2wAo0RCmwOXNNeZt478U1Pm__ybdWraPMgSNLwv4TcoKwoA3-LM84AF-U5NVCsX9RFDeWA6Qu7fWTDWb1wHhYhnE7fEnzWTT_PT7tbwGI4lOMTcALPn9ccsG7pA98DadSKuwU5e3ZcqDLBJRHwHeuJLcKoOkNPgqNFN45SDozd__LCdAOIxmy2jXlPaF4qxnlOYF4TgcRLXmP-VZlVTGZKABw0i2Ycb4MP1xa6_tn6FGsYZI4FES5FzS4YezHkaZwd56agqWNQ',
        p:
         '510aPijCuIWYrBMCKf0-rdprZ7hDJ6-kJemYbrv0pQIBK9jah9gdwKCZ9xJqEAJZT-f2-qGHUpNUQJDAlpqWRM7NcbYGkVewz7Hey-dURg2iRKn_upP5IzJB0L5NIcaHo_G8Aw76lUwRSr2O1TqKEKlVexmOiMouFUyLs128ha8',
        q:
         'wEnQcV_AiKUpzvvPrw5eyZm9uC9e-IPvryH5h2Rtg0_DO4CbiOtUbF-Y_bFjE71mAfPMrm7E7B_LENpzCctGwu05QCddRt2I5aXvGh__8YytatOckU7gOO_CncmYWLCUIAK9zWiu_V0WWDahJ-o8PFx7yG_dOt4JjE8Samt-zc8',
        dp:
         'O2EVvyZO83S2PlOSlpw8XfpU3oXYFnNpuaE-Ug1DOKZPDqXVUFATMsEFQvgi6IDx0yRBqwmR5YuScA-2nfCG6Jn6-FgzT1ImOuf3unVgl6ogH2dSDtyzcGkRozV0Llr5rQX5rv9FKNQhDAGiiu8_SA9ttO5WOp1JPoYqxJomLFk',
        dq:
         'UlIHi9H7YkSbPoKtaftT9yj7gNO-69PIFAkOg7kp7TKDmYC4lYhyDydqHwoHKZdHCYTvVqoTYidGT0PGRiYheCgI_38avtDu36oHT_7tGuMoBvjrKYZEFfwHLHf24dlOwNmLmlm7uLpWa5OPsL_l482QLMI_SwltuwTLFIZKth8',
        qi:
         'B2VcI2Nz8y5BF7omGLbf-quBzYZsnWi45fA4R95OfOEjAkYXEZ4SzY52M2h1Nfwj5xIA45Fk0kalvRG3xBSvp28AHAgUunodryeThx9WFYYFj0bomeY0q3DJ5SLLQWZLn5v8pXx_InHC9oygCeX7xLFqcADE5q-g8X11Ms0IKMI' },
     _publicKey:
      { kty: 'RSA',
        n:
         'rciJnTZAToh-9FRF-6kZyICUGy6OJlb-Nv0SjoS3U_SJxUymVIoqMOOPFW-2lIXjxS-iPfVwi7CLl60MkxFllJUs5sF5nJU5KwR2CXusniI3h34X2igkWQuNe5EqwJw53rg2kaLcceNoWYGw1Xogv_okWnjaSDvo4HYUDWLyLf4mtP_Xwowi9IzH4qw99IPPjo0yA9KNxa1ZxjN9zdMsDcE9tmh9iUoh3-50m3LziVyQ7pgEto6p3xM72cfMY7PuiEihLa6Lbt0RGmGmxnroLrY-aenXRsbjJzRVdFUq5xoYuZhCH_gfcgXU3KgmZW2nizvX0xttzK5FsC84s587gQ',
        e: 'AQAB' } },
  _pubKey:
   RsaPublicKey {
     _key:
      { kty: 'RSA',
        n:
         'rciJnTZAToh-9FRF-6kZyICUGy6OJlb-Nv0SjoS3U_SJxUymVIoqMOOPFW-2lIXjxS-iPfVwi7CLl60MkxFllJUs5sF5nJU5KwR2CXusniI3h34X2igkWQuNe5EqwJw53rg2kaLcceNoWYGw1Xogv_okWnjaSDvo4HYUDWLyLf4mtP_Xwowi9IzH4qw99IPPjo0yA9KNxa1ZxjN9zdMsDcE9tmh9iUoh3-50m3LziVyQ7pgEto6p3xM72cfMY7PuiEihLa6Lbt0RGmGmxnroLrY-aenXRsbjJzRVdFUq5xoYuZhCH_gfcgXU3KgmZW2nizvX0xttzK5FsC84s587gQ',
        e: 'AQAB' } },
  _idCIDString:
   'bafzbeicxbbma67bs5ss642fqvu4zd2arb57wg2nxdpgct5cbtvfnkzv7ca' }
Listening on 
	- /ip4/127.0.0.1/tcp/46155
	- /ip4/192.168.50.179/tcp/46155
Subscribed to waku relay
Dialing /ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ
Please choose a nickname: oskar
(node:42347) UnhandledPromiseRejectionWarning: oskar
(node:42347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:42347) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

1) Verbose logs
2) Unhandled promises

**Comment by D4nte** [comment]
> Installing buf from [docs.buf.build/installation](https://docs.buf.build/installation/) (Linux) seems OK but a bit annoying from developer XP POV.

I can check in the generated files so one only need it if they change the proto files.
In terms of dev xp, this is of course only needed for js-waku developers. Users of the library will just need to install the js-waku package. 

> How much do we need it? As a JS developer I'd probably rather write JSON and leave protobuf as an implementation detail.

I am not sure if your POV is js-waku maintainer or consumer of js-waku. I tried a couple TypeScript libs for proto and they both needed protobuf.

> 1. Verbose logs

Yes, already wip in #37.


> 2. Unhandled promises

That's interesting, did you just enter your nickname and the error appeared?

**Comment by oskarth** [comment]
> I tried a couple TypeScript libs for proto and they both needed protobuf.

Ack

> did you just enter your nickname and the error appeared?

Yes
