### ISSUE TITLE
[cli chat] Error: stream ended before 1 bytes became available

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#46]
```
╭─petty@bean in ~/GitHub/status-im/js-waku on main ✘ (origin/main)
╰$ npm run chat -- --staticNode /ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ

> js-waku@1.0.0 chat
> ts-node src/chat/index.ts "--staticNode" "/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"

PeerId:  QmSZ1HxMUrKLGWetceEk93E2p4f2ppnzU927GUF9Mya5pL
Listening on 
	- /ip4/127.0.0.1/tcp/41475
	- /ip4/192.168.1.222/tcp/41475
	- /ip4/172.25.122.232/tcp/41475
Please choose a nickname: petty
Using default nick.
Hi, js-waku!
Dialing /ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ

/home/petty/GitHub/status-im/js-waku/node_modules/p-some/index.js:31
			reject(new AggregateError(errors));
          ^
AggregateError: 
    Error: stream ended before 1 bytes became available
        at /home/petty/GitHub/status-im/js-waku/node_modules/it-reader/index.js:37:9
        at processTicksAndRejections (node:internal/process/task_queues:94:5)
        at /home/petty/GitHub/status-im/js-waku/node_modules/it-length-prefixed/src/decode.js:80:20
        at oneChunk (/home/petty/GitHub/status-im/js-waku/node_modules/multistream-select/src/multistream.js:12:20)
        at Object.exports.read (/home/petty/GitHub/status-im/js-waku/node_modules/multistream-select/src/multistream.js:34:15)
        at module.exports (/home/petty/GitHub/status-im/js-waku/node_modules/multistream-select/src/select.js:21:19)
        at Upgrader._encryptOutbound (/home/petty/GitHub/status-im/js-waku/node_modules/libp2p/src/upgrader.js:385:36)
        at Upgrader.upgradeOutbound (/home/petty/GitHub/status-im/js-waku/node_modules/libp2p/src/upgrader.js:167:11)
        at ClassIsWrapper.dial (/home/petty/GitHub/status-im/js-waku/node_modules/libp2p-tcp/src/index.js:42:18)
        at TransportManager.dial (/home/petty/GitHub/status-im/js-waku/node_modules/libp2p/src/transport-manager.js:111:14)
    at maybeSettle (/home/petty/GitHub/status-im/js-waku/node_modules/p-some/index.js:31:11)
    at /home/petty/GitHub/status-im/js-waku/node_modules/p-some/index.js:69:23
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR! code 1
npm ERR! path /home/petty/GitHub/status-im/js-waku
npm ERR! command failed
npm ERR! command sh -c ts-node src/chat/index.ts "--staticNode" "/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/petty/.npm/_logs/2021-04-20T20_40_06_776Z-debug.log
```

Cc @corpetty

**Comment by D4nte** [comment]
Could I please have:
- OS
- Node version

**Comment by D4nte** [comment]
Current priority for js-waku is browser environment.
Do note that in my testing, I noticed issues with NodeJS version 12 & 13. Be sure to use 14 or above.
