### ISSUE TITLE
Changes merged in master are not deployed on js-waku.wakuconnect.dev

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#556]
This is a **bug report**

## Problem

The latest changes merged on master are not deployed to https://js-waku.wakuconnect.dev/. I noticed because the function `hexToBytes` is missing from the documentation.

It looks like only changes from the `build-examples` branch are deployed: https://ci.status.im/job/website/job/js-waku.wakuconnect.dev/lastBuild/

@jakubgs can you please assist?

**Comment by jakubgs** [comment]
Indeed, the hook still remembers the old branch:
```
[poll] Last Built Revision: Revision b4a582a692b9a1fa34071501e125fb4ccc604268 (refs/remotes/origin/ci/build-examples)
```
https://ci.status.im/job/website/job/js-waku.wakuconnect.dev/GitHubPollLog/

But the config already uses `master`. Although a manually started build fails with:
```
Error when executing always post condition:
org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:89)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
https://ci.status.im/job/website/job/js-waku.wakuconnect.dev/63/console

Seems like a syntax error in the Jenkinsfile.

**Comment by jakubgs** [comment]
Oh wait, no, the branch is still wrong in the config:

![image](https://user-images.githubusercontent.com/2212681/154930230-935a8546-8cf9-4e02-a73e-bb196e3c436d.png)

It wasn't changed after the PR was merged.

**Comment by jakubgs** [comment]
I've changed it, but you should also have permissions to change that.
But I also found a wrong branch name in the condition: https://github.com/status-im/js-waku/commit/c6081185

New build works fine: https://ci.status.im/job/website/job/js-waku.wakuconnect.dev/65/
