### ISSUE TITLE
Bug: handshakes with peers don't work

### ISSUE THREAD

**Issue by filoozom** [status-im/js-waku#889]
This is a **bug report**

## Problem

Handshakes with peers don't work, making it impossible for `js-waku` to communicate with any other node.

The code is very basic:
```ts
const waku = await Waku.create({
	bootstrap: {
		peers: ['/dns4/private.domain/tcp/443/wss/p2p/16Uiu2HAkwAzaMhKTikSVD1djSieWNoJ9jq63kmJG21mmizT8jQDq']
	}
})
await waku.waitForRemotePeer()
```

The logs in the browser:

```
libp2p:websockets dialing /dns4/private.domain/tcp/443/wss/p2p/16Uiu2HAkwAzaMhKTikSVD1djSieWNoJ9jq63kmJG21mmizT8jQDq +10s
common.js:113 libp2p:websockets dialing private.domain:443 +0ms
common.js:113 libp2p:websockets connected /dns4/private.domain/tcp/443/wss/p2p/16Uiu2HAkwAzaMhKTikSVD1djSieWNoJ9jq63kmJG21mmizT8jQDq +115ms
common.js:113 libp2p:websockets new outbound connection /dns4/private.domain/tcp/443/wss/p2p/16Uiu2HAkwAzaMhKTikSVD1djSieWNoJ9jq63kmJG21mmizT8jQDq +0ms
common.js:113 libp2p:upgrader Starting the outbound connection upgrade +10s
common.js:113 libp2p:upgrader selecting outbound crypto protocol +0ms ['/noise']
common.js:113 mss:select select: write ["/multistream/1.0.0", "/noise"] +10s
common.js:113 mss:select select: read "/multistream/1.0.0" +1ms
common.js:113 mss:select select: read "/noise" +40ms
common.js:113 libp2p:upgrader encrypting outbound connection to {"id":"16Uiu2HAkwAzaMhKTikSVD1djSieWNoJ9jq63kmJG21mmizT8jQDq","pubKey":"CAISIQIZ9LAuNEcxirgJRqJj0FedIiUS7AA1A0URms+svcgYJA=="} +41ms
common.js:113 libp2p:noise Stage 0 - Initiator starting to send first message. +10s
common.js:113 libp2p:noise Stage 0 - Initiator finished sending first message. +1ms
common.js:113 libp2p:noise Stage 1 - Initiator waiting to receive first message from responder... +0ms
common.js:113 libp2p:upgrader:err Failed to upgrade outbound connection +10s Error: Error occurred during XX handshake: First argument to DataView constructor must be an ArrayBuffer
    at Noise.performXXHandshake (noise.ts:210:13)
    at async Noise.performHandshake (noise.ts:166:14)
    at async Noise.secureOutbound (noise.ts:79:23)
    at async Upgrader._encryptOutbound (upgrader.js:436:12)
    at async Upgrader.upgradeOutbound (upgrader.js:196:11)
    at async ClassIsWrapper.dial (index.js:54:18)
    at async TransportManager.dial (transport-manager.js:111:14)
    at async dial-request.js:81:18
    at async index.js:53:19
common.js:113 libp2p:dialer token 16 released +222ms
common.js:113 libp2p:dialer:err AggregateError:     Error: Error occurred during XX handshake: First argument to DataView constructor must be an ArrayBuffer        at Noise.performXXHandshake (http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:35151:17)        at async Noise.performHandshake (http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:35122:18)        at async Noise.secureOutbound (http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:35062:27)        at async Upgrader._encryptOutbound (http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:51563:16)        at async Upgrader.upgradeOutbound (http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:51401:15)        at async ClassIsWrapper.dial (http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:63545:22)        at async TransportManager.dial (http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:38975:18)        at async http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:41790:22        at async http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:41695:27    at maybeSettle (http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:41678:18)    at http://localhost:5173/node_modules/.vite/deps/js-waku.js?v=4015e773:41707:31 +10s
common.js:113 libp2p:connection-manager:auto-dialler:err could not connect to peerStore stored peer +10s AggregateError: 
    Error: Error occurred during XX handshake: First argument to DataView constructor must be an ArrayBuffer
        at Noise.performXXHandshake (noise.ts:210:13)
        at async Noise.performHandshake (noise.ts:166:14)
        at async Noise.secureOutbound (noise.ts:79:23)
        at async Upgrader._encryptOutbound (upgrader.js:436:12)
        at async Upgrader.upgradeOutbound (upgrader.js:196:11)
        at async ClassIsWrapper.dial (index.js:54:18)
        at async TransportManager.dial (transport-manager.js:111:14)
        at async dial-request.js:81:18
        at async index.js:53:19
    at maybeSettle (index.js:31:11)
    at index.js:69:23
```

## Notes

Running `js-waku` `0.24.0`.
Details for `libp2p` dependencies:
```
│ ├─┬ @chainsafe/libp2p-noise@5.0.3
│ ├─┬ libp2p-bootstrap@0.14.0
│ ├─┬ libp2p-crypto@0.21.2
│ ├─┬ libp2p-gossipsub@0.13.0
│ │ ├── libp2p-interfaces@4.0.6 deduped
│ ├─┬ libp2p-interfaces@4.0.6
│ │ ├── libp2p-crypto@0.21.2 deduped
│ ├─┬ libp2p-mplex@0.10.7
│ ├─┬ libp2p-websockets@0.16.2
│ │ ├─┬ libp2p-utils@0.4.1
│ ├─┬ libp2p@0.36.2
│ │ ├── libp2p-crypto@0.21.2 deduped
│ │ ├── libp2p-interfaces@4.0.6 deduped
│ │ ├── libp2p-utils@0.4.1 deduped
│ │ ├── libp2p-crypto@0.21.2 deduped
```

It also doesn't work from `0.21.0` to `0.23.0` or with `{ boostrap: { default: true } }`, so probably linked to my ViteJS config...

**Comment by fryorcraken** [comment]
I believe it is fixed with `js-waku@next`, right?

**Comment by filoozom** [comment]
> I believe it is fixed with `js-waku@next`, right?

Absolutely, although it would still be nice to figure out why it doesn't work with previous versions anymore, so it doesn't happen again. Maybe dependency pinning?

**Comment by fryorcraken** [comment]
> > I believe it is fixed with `js-waku@next`, right?
> 
> Absolutely, although it would still be nice to figure out why it doesn't work with previous versions anymore, so it doesn't happen again. Maybe dependency pinning?
> 
> For example, this project from 4 months ago doesn't work anymore despite nothing having changed: [swarmcity/shortcodes-demo](https://github.com/swarmcity/shortcodes-demo)
> 
> ```
> git clone https://github.com/swarmcity/shortcodes-demo[](https://github.com/swarmcity/shortcodes-demo)
> cd shortcodes-demo
> npm i
> npm run dev
> ```
> 
> It's not the same error I believe, but it still doesn't work anymore.

Some of js-waku's dependencies have mis-managed version bumping and introduced breaking changes in patch/minor bump.
Hence, such behaviour has been encountered.

I am not sure there is much I can do from js-waku PoV as I already check in the `package-lock.json` file. Thoughts?

**Comment by fryorcraken** [comment]
Maybe using version override or locking in the `package.json` file would help.

**Comment by fryorcraken** [comment]
Won't fix because we do not guarantee support for older versions in this phase of development.
